name: CI/CD MLFlow

permissions:
    contents: write

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                persist-credentials: true
                fetch-depth: 0


            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12.7"


            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install mlflow pandas numpy scikit-learn matplotlib
                  
            - name: Run mlflow
              run: |
                  mlflow run MLProject --env-manager=local
            
            - name: Debug mlruns contents
              run: |
                  echo "Listing mlruns directory:"
                  ls -R mlruns/
                          
            - name: Get latest MLflow run_id
              run: |
                   echo "RUN_ID=$(ls -td mlruns/0/*/ | head -n1 | xargs basename)" >> $GITHUB_ENV

            - name: Install Git LFS
              run: |
                    sudo apt-get update && sudo apt-get install git-lfs -y
                    git lfs install

            - name: Track MLflow model artifacts
              run: |
                ls -R mlruns/0/$RUN_ID/artifacts/model
                git lfs track "mlruns/0/$RUN_ID/artifacts/model/**"
                git add .gitattributes

            - name: Configure Git user
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Commit MLflow artifacts
              run: |
                git add -f mlruns/0/$RUN_ID/artifacts/model/**
                git diff --quiet && echo "No new artifacts to commit" || git commit -m "chore: add MLflow model artifacts for run $RUN_ID [skip ci]"

            - name: Push artifacts to GitHub
              run: git push -u origin main

            # - name: Build Docker Model
            #   run: |
            #     mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "ss-model" 

            # # Login to Docker Hub
            # - name: Log in to Docker Hub
            #   uses: docker/login-action@v2
            #   with:
            #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
            #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            # # Tag the Docker image
            # - name: Tag Docker Image
            #   run: |
            #     docker tag ss-model ${{ secrets.DOCKER_HUB_USERNAME }}/ss-model:latest

            # # Push Docker image to Docker Hub
            # - name: Push Docker Image
            #   run: |
            #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ss-model:latest