name: CI/CD MLFlow

permissions:
    contents: write

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
env:
  CSV_URL: "MLproject/supplement_sales_preprocessed/sales_train_preprocessed.csv"
  TARGET_VAR: "Revenue"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                persist-credentials: true
                fetch-depth: 0
                lfs: true
            - name: Check Env
              run: |
                  echo "CSV_URL: $CSV_URL"
                  echo "TARGET_VAR: $TARGET_VAR"

            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12.7"


            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install mlflow pandas numpy scikit-learn matplotlib
                  
            - name: Run mlflow
              run: |
                  mlflow run MLProject --env-manager=local
            
            - name: Debug mlruns contents
              run: |
                  echo "Listing mlruns directory:"
                  ls -R mlruns/
                          
            - name: Get latest MLflow run_id
              run: |
                   echo "RUN_ID=$(ls -td mlruns/0/*/ | head -n1 | xargs basename)" >> $GITHUB_ENV

            - name: Set up Git LFS
              run: |
                git config --global user.name ${{ secrets.username }}
                git config --global user.email ${{ secrets.email }}
                git lfs install
                git lfs track "mlruns/**"
                git add .gitattributes
                git commit -m "Track large files in mlruns with Git LFS" || true
                git push origin main
          
       # Save models to GitHub Repository
            - name: Save mlruns to repo
              run: |
                git config --global user.name ${{ secrets.username }}
                git config --global user.email ${{ secrets.email }}
                git add -f mlruns/
                git commit -m "Save mlruns from CI run" || true
                git push origin main

            # Login to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            # Tag the Docker image
            - name: Tag Docker Image
              run: |
                docker tag ss-model ${{ secrets.DOCKER_HUB_USERNAME }}/ss-model:latest

            # Push Docker image to Docker Hub
            - name: Push Docker Image
              run: |
                docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ss-model:latest